### ISSUE TITLE
Python not found

### ISSUE THREAD

**Issue by Piste** [fiatjaf/branle#35]
Getting the below when building Docker image. Me only? 
```
#12 27.60 [5/5] Building fresh packages...
#12 28.09 error /app/build/node_modules/utf-8-validate: Command failed.
#12 28.09 Exit code: 1
#12 28.09 Command: node-gyp-build
#12 28.09 Arguments:
#12 28.09 Directory: /app/build/node_modules/utf-8-validate
#12 28.09 Output:
#12 28.09 gyp info it worked if it ends with ok
#12 28.09 gyp info using node-gyp@5.1.0
#12 28.09 gyp info using node@12.22.11 | linux | arm64
#12 28.09 gyp ERR! find Python
#12 28.09 gyp ERR! find Python Python is not set from command line or npm configuration
#12 28.09 gyp ERR! find Python Python is not set from environment variable PYTHON
#12 28.09 gyp ERR! find Python checking if "python" can be used
#12 28.09 gyp ERR! find Python - "python" is not in PATH or produced an error
#12 28.09 gyp ERR! find Python checking if "python2" can be used
#12 28.09 gyp ERR! find Python - "python2" is not in PATH or produced an error
#12 28.09 gyp ERR! find Python checking if "python3" can be used
#12 28.09 gyp ERR! find Python - "python3" is not in PATH or produced an error
#12 28.09 gyp ERR! find Python
#12 28.09 gyp ERR! find Python **********************************************************
#12 28.09 gyp ERR! find Python You need to install the latest version of Python.
#12 28.09 gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#12 28.09 gyp ERR! find Python you can try one of the following options:
#12 28.09 gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#12 28.09 gyp ERR! find Python   (accepted by both node-gyp and npm)
#12 28.09 gyp ERR! find Python - Set the environment variable PYTHON
#12 28.09 gyp ERR! find Python - Set the npm configuration variable python:
#12 28.09 gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#12 28.09 gyp ERR! find Python For more information consult the documentation at:
#12 28.09 gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#12 28.09 gyp ERR! find Python **********************************************************
#12 28.09 gyp ERR! find Python
#12 28.09 gyp ERR! configure error
#12 28.09 gyp ERR! stack Error: Could not find any Python installation to use
#12 28.09 gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
#12 28.09 gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
#12 28.09 gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
#12 28.09 gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
#12 28.09 gyp ERR! stack     at exithandler (child_process.js:315:5)
#12 28.09 gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:327:5)
#12 28.09 gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
#12 28.09 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
#12 28.09 gyp ERR! stack     at onErrorNT (internal/child_process.js:470:16)
#12 28.09 gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
#12 28.09 gyp ERR! System Linux 5.10.104-linuxkit
#12 28.09 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
#12 28.09 gyp ERR! cwd /app/build/node_modules/utf-8-validate
#12 28.09 gyp ERR! node -v v12.22.11
#12 28.09 gyp ERR! node-gyp -v v5.1.0
#12 28.09 gyp ERR! not ok
#12 28.09 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
executor failed running [/bin/sh -c yarn]: exit code: 1

```

**Comment by fiatjaf** [comment]
Sorry, JavaScript is stupid and this bug is out of the scope of this repo.

**Comment by monlovesmango** [comment]
I think fiatjaf might have python already installed or something locally. I fixed this by replacing 'RUN yarn' with:
```# --no-cache: download package index on-the-fly, no need to cleanup afterwards
# --virtual: bundle packages, remove whole bundle at once, when done
RUN apk --no-cache --virtual build-dependencies add \
  python3 \
  make \
  g++ \
  && yarn \
  && apk del build-dependencies
```
in my docker file. basically temporarily installs the needed dependencies to 'RUN yarn' and then deletes them so it doesn't bloat your memory.

**Comment by fiatjaf** [comment]
Thank you very much @monlovesmango.
